const db = require('./lowdb');

const initIngredientData = () => {
  const existing = db.get('ingredients').value();
  if (existing.length === 0) {
    const vietnameseIngredients = [
      // Nhóm ngũ cốc
      { 
        id: 'ing-001', 
        name: 'Gạo tẻ', 
        category: 'grains', 
        calories: 130, 
        protein: 2.7, 
        carbs: 28, 
        fat: 0.3, 
        fiber: 0.4, 
        sugar: 0.1,
        sodium: 5,
        unit: '100g', 
        price: 25000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-002', 
        name: 'Gạo lứt', 
        category: 'grains', 
        calories: 123, 
        protein: 2.6, 
        carbs: 23, 
        fat: 0.9, 
        fiber: 1.8, 
        sugar: 0.4,
        sodium: 7,
        unit: '100g', 
        price: 35000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-003', 
        name: 'Bánh phở', 
        category: 'grains', 
        calories: 109, 
        protein: 0.9, 
        carbs: 25, 
        fat: 0.2, 
        fiber: 0.8, 
        sugar: 0.2,
        sodium: 3,
        unit: '100g', 
        price: 15000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-004', 
        name: 'Bún tươi', 
        category: 'grains', 
        calories: 108, 
        protein: 0.8, 
        carbs: 25, 
        fat: 0.1, 
        fiber: 0.6, 
        sugar: 0.1,
        sodium: 5,
        unit: '100g', 
        price: 12000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      
      // Nhóm thịt
      { 
        id: 'ing-005', 
        name: 'Thịt bò nạc', 
        category: 'meat', 
        calories: 250, 
        protein: 26, 
        carbs: 0, 
        fat: 15, 
        fiber: 0, 
        sugar: 0,
        sodium: 65,
        unit: '100g', 
        price: 350000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-006', 
        name: 'Thịt heo nạc', 
        category: 'meat', 
        calories: 242, 
        protein: 27, 
        carbs: 0, 
        fat: 14, 
        fiber: 0, 
        sugar: 0,
        sodium: 62,
        unit: '100g', 
        price: 180000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-007', 
        name: 'Thịt gà ta', 
        category: 'meat', 
        calories: 239, 
        protein: 27, 
        carbs: 0, 
        fat: 14, 
        fiber: 0, 
        sugar: 0,
        sodium: 70,
        unit: '100g', 
        price: 120000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-008', 
        name: 'Sườn heo', 
        category: 'meat', 
        calories: 297, 
        protein: 25, 
        carbs: 0, 
        fat: 21, 
        fiber: 0, 
        sugar: 0,
        sodium: 58,
        unit: '100g', 
        price: 160000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      
      // Nhóm hải sản
      { 
        id: 'ing-009', 
        name: 'Cá thu', 
        category: 'seafood', 
        calories: 184, 
        protein: 25, 
        carbs: 0, 
        fat: 8.5, 
        fiber: 0, 
        sugar: 0,
        sodium: 59,
        unit: '100g', 
        price: 200000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-010', 
        name: 'Cá hồi', 
        category: 'seafood', 
        calories: 208, 
        protein: 25, 
        carbs: 0, 
        fat: 12, 
        fiber: 0, 
        sugar: 0,
        sodium: 59,
        unit: '100g', 
        price: 450000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-011', 
        name: 'Tôm sú', 
        category: 'seafood', 
        calories: 106, 
        protein: 20, 
        carbs: 0.9, 
        fat: 1.7, 
        fiber: 0, 
        sugar: 0,
        sodium: 111,
        unit: '100g', 
        price: 380000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-012', 
        name: 'Cua biển', 
        category: 'seafood', 
        calories: 97, 
        protein: 19, 
        carbs: 0, 
        fat: 1.5, 
        fiber: 0, 
        sugar: 0,
        sodium: 293,
        unit: '100g', 
        price: 250000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      
      // Nhóm rau củ
      { 
        id: 'ing-013', 
        name: 'Cà rót', 
        category: 'vegetables', 
        calories: 25, 
        protein: 1, 
        carbs: 6, 
        fat: 0.2, 
        fiber: 3, 
        sugar: 3.5,
        sodium: 2,
        unit: '100g', 
        price: 15000, 
        season: 'summer',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-014', 
        name: 'Cà chua', 
        category: 'vegetables', 
        calories: 18, 
        protein: 0.9, 
        carbs: 3.9, 
        fat: 0.2, 
        fiber: 1.2, 
        sugar: 2.6,
        sodium: 5,
        unit: '100g', 
        price: 20000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-015', 
        name: 'Rau muống', 
        category: 'vegetables', 
        calories: 19, 
        protein: 2.6, 
        carbs: 2.1, 
        fat: 0.2, 
        fiber: 2.1, 
        sugar: 0.9,
        sodium: 113,
        unit: '100g', 
        price: 8000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-016', 
        name: 'Bông cải xanh', 
        category: 'vegetables', 
        calories: 34, 
        protein: 2.8, 
        carbs: 7, 
        fat: 0.4, 
        fiber: 2.6, 
        sugar: 1.5,
        sodium: 33,
        unit: '100g', 
        price: 25000, 
        season: 'winter',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-017', 
        name: 'Cà rốt', 
        category: 'vegetables', 
        calories: 41, 
        protein: 0.9, 
        carbs: 10, 
        fat: 0.2, 
        fiber: 2.8, 
        sugar: 4.7,
        sodium: 69,
        unit: '100g', 
        price: 18000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-018', 
        name: 'Khoai lang', 
        category: 'vegetables', 
        calories: 86, 
        protein: 1.6, 
        carbs: 20, 
        fat: 0.1, 
        fiber: 3, 
        sugar: 4.2,
        sodium: 54,
        unit: '100g', 
        price: 12000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      
      // Nhóm trái cây
      { 
        id: 'ing-019', 
        name: 'Chuối tiêu', 
        category: 'fruits', 
        calories: 89, 
        protein: 1.1, 
        carbs: 23, 
        fat: 0.3, 
        fiber: 2.6, 
        sugar: 12.2,
        sodium: 1,
        unit: '100g', 
        price: 25000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-020', 
        name: 'Táo ta', 
        category: 'fruits', 
        calories: 52, 
        protein: 0.3, 
        carbs: 14, 
        fat: 0.2, 
        fiber: 2.4, 
        sugar: 10.4,
        sodium: 1,
        unit: '100g', 
        price: 45000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-021', 
        name: 'Xoài cát', 
        category: 'fruits', 
        calories: 60, 
        protein: 0.8, 
        carbs: 15, 
        fat: 0.4, 
        fiber: 1.6, 
        sugar: 13.7,
        sodium: 1,
        unit: '100g', 
        price: 35000, 
        season: 'summer',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-022', 
        name: 'Ổi', 
        category: 'fruits', 
        calories: 68, 
        protein: 2.6, 
        carbs: 14, 
        fat: 1, 
        fiber: 5.4, 
        sugar: 8.9,
        sodium: 2,
        unit: '100g', 
        price: 20000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      
      // Nhóm gia vị
      { 
        id: 'ing-023', 
        name: 'Hành tím', 
        category: 'spices', 
        calories: 40, 
        protein: 1.1, 
        carbs: 9.3, 
        fat: 0.1, 
        fiber: 1.7, 
        sugar: 4.2,
        sodium: 4,
        unit: '100g', 
        price: 30000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-024', 
        name: 'Tỏi', 
        category: 'spices', 
        calories: 149, 
        protein: 6.4, 
        carbs: 33, 
        fat: 0.5, 
        fiber: 2.1, 
        sugar: 1,
        sodium: 17,
        unit: '100g', 
        price: 80000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-025', 
        name: 'Gừng', 
        category: 'spices', 
        calories: 80, 
        protein: 1.8, 
        carbs: 18, 
        fat: 0.8, 
        fiber: 2, 
        sugar: 1.7,
        sodium: 13,
        unit: '100g', 
        price: 60000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-026', 
        name: 'Sả', 
        category: 'spices', 
        calories: 99, 
        protein: 1.8, 
        carbs: 25, 
        fat: 0.5, 
        fiber: 7.6, 
        sugar: 0,
        sodium: 6,
        unit: '100g', 
        price: 25000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      
      // Nhóm đậu và hạt
      { 
        id: 'ing-027', 
        name: 'Đậu phụ', 
        category: 'legumes', 
        calories: 76, 
        protein: 8, 
        carbs: 1.9, 
        fat: 4.8, 
        fiber: 0.4, 
        sugar: 0.6,
        sodium: 7,
        unit: '100g', 
        price: 15000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-028', 
        name: 'Đậu xanh', 
        category: 'legumes', 
        calories: 347, 
        protein: 23, 
        carbs: 63, 
        fat: 1.2, 
        fiber: 16, 
        sugar: 7,
        sodium: 15,
        unit: '100g', 
        price: 40000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-029', 
        name: 'Đậu đỏ', 
        category: 'legumes', 
        calories: 333, 
        protein: 20, 
        carbs: 61, 
        fat: 1.1, 
        fiber: 12, 
        sugar: 2.2,
        sodium: 12,
        unit: '100g', 
        price: 45000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-030', 
        name: 'Lạc rang', 
        category: 'nuts', 
        calories: 567, 
        protein: 26, 
        carbs: 16, 
        fat: 49, 
        fiber: 8.5, 
        sugar: 4.7,
        sodium: 18,
        unit: '100g', 
        price: 70000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      
      // Nhóm sữa và trứng
      { 
        id: 'ing-031', 
        name: 'Trứng gà', 
        category: 'dairy', 
        calories: 155, 
        protein: 13, 
        carbs: 1.1, 
        fat: 11, 
        fiber: 0, 
        sugar: 1.1,
        sodium: 124,
        unit: '100g', 
        price: 35000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-032', 
        name: 'Sữa tươi', 
        category: 'dairy', 
        calories: 61, 
        protein: 3.2, 
        carbs: 4.8, 
        fat: 3.3, 
        fiber: 0, 
        sugar: 5.1,
        sodium: 44,
        unit: '100ml', 
        price: 25000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-033', 
        name: 'Sữa chua', 
        category: 'dairy', 
        calories: 59, 
        protein: 3.5, 
        carbs: 4.7, 
        fat: 3.3, 
        fiber: 0, 
        sugar: 4.7,
        sodium: 46,
        unit: '100g', 
        price: 8000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      
      // Nhóm dầu ăn
      { 
        id: 'ing-034', 
        name: 'Dầu ăn', 
        category: 'oils', 
        calories: 884, 
        protein: 0, 
        carbs: 0, 
        fat: 100, 
        fiber: 0, 
        sugar: 0,
        sodium: 0,
        unit: '100ml', 
        price: 45000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      { 
        id: 'ing-035', 
        name: 'Dầu oliu', 
        category: 'oils', 
        calories: 884, 
        protein: 0, 
        carbs: 0, 
        fat: 100, 
        fiber: 0, 
        sugar: 0,
        sodium: 2,
        unit: '100ml', 
        price: 180000, 
        season: 'all',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
    ];

    db.get('ingredients').push(...vietnameseIngredients).write();
    console.log('✅ Vietnamese ingredients data seeded successfully!');
  }
};

module.exports = { initIngredientData };
